package x.flyspace.mybatisgenerator.comment;

import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.internal.DefaultCommentGenerator;
import org.mybatis.generator.internal.util.StringUtility;

import java.util.Properties;
import java.util.Scanner;

/**
 * Created by sky91 on 12/24/14.
 */
public class CommentGenerator extends DefaultCommentGenerator {
	private boolean suppressAllComments;

	@Override
	public void addConfigurationProperties(Properties properties) {
		super.addConfigurationProperties(properties);
		this.suppressAllComments = StringUtility.isTrue(properties.getProperty("suppressAllComments"));
	}

	@Override
	public void addFieldComment(Field field, IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn) {
		if(this.suppressAllComments) {
			return;
		}
		StringBuilder sb = new StringBuilder();
		field.addJavaDocLine("/**");
		field.addJavaDocLine(" * This field was generated by MyBatis Generator.");
		sb.append(" * This field corresponds to the database column ");
		sb.append(introspectedTable.getFullyQualifiedTable());
		sb.append('.');
		sb.append(introspectedColumn.getActualColumnName());
		field.addJavaDocLine(sb.toString());
		Scanner scanner = new Scanner(introspectedColumn.getRemarks());
		while(scanner.hasNextLine()) {
			field.addJavaDocLine(" * " + scanner.nextLine());
		}
		addJavadocTag(field, false);
		field.addJavaDocLine(" */");
	}
}
